openapi: "3.0.3"
info:
  title: 42_Matcha API
  version: "1.0"
servers:
  - url: https://api.server.test/v1

components:
  parameters:
    BearerAuth:
      in: header
      name: Authorization
      required: true
      schema:
        type: string
        example: "Bearer <token>"

paths:
  /auth/login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            example:
              username: "user123"
              password: "password123"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              example:
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
        "400":
          description: Missing required fields
        "401":
          description: Incorrect email or password

  /auth/register:
    post:
      requestBody:
        required: true
        content:
          application/json:
            example:
              first_name: "test"
              last_name: "user"
              email: "user@email.com"
              username: "user123"
              password: "password123"
      responses:
        "200":
          description: Sign up successful
        "400":
          description: Invalid or missing required fields
          content:
            application/json:
              examples:
                missingFields:
                  value:
                    errorCode: 0
                    message: "Missing required fields"
                weakPassword:
                  value:
                    errorCode: 1
                    message: "Password is too weak"
        "409":
          description: User already exists

  /auth/forgot-password:
    post:
      description: Request password reset email
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: "user@email.com"
      responses:
        "201":
          description: Accepted
        "400":
          description: Missing required fields
        "409":
          description: User does not exist

  /auth/reset-password:
    post:
      description: Change password after getting reset email
      parameters:
        - name: token
          in: query
          required: true
      requestBody:
        required: true
        content:
          application/json:
            example:
              newPassword: "oldpassword123"
              resetToken: ""
      responses:
        "200":
          description: Password changed
        "400":
          description: Invalid or missing required fields
          content:
            application/json:
              examples:
                missingFields:
                  value:
                    errorCode: 0
                    message: "Missing required fields"
                weakPassword:
                  value:
                    errorCode: 1
                    message: "Password is too weak"

  /auth/verify:
    get:
      description: Verify account after getting verification email
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Verified

  /profile/me:
    get:
      parameters:
        - $ref: "#/components/parameters/BearerAuth"
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                profile:
                  firstname: "test_first"
                  lastname: "test_last"
                  username: "test_username"
                  picture: "http://localhost:5001/image/profile.jpg"
                isProfileCompleted: true
                notifications: []

  /profile/update:
    get:
      parameters:
        - $ref: "#/components/parameters/BearerAuth"
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                firstname: "firstname"
                lastname: "lastname"
                email: "user@email.com"
                date_of_birth: "01/01/2000"
                gender: "male"
                preference: "female"
                fame: 10
                biography: "this is my biography"
                interest:
                  - "one"
                  - "two"
                  - "three"
                  - "four"
                  - "five"
                pictures:
                  - "http://localhost:5001/image/profile.jpg"
                  - "http://localhost:5001/image/one.jpg"
                  - "http://localhost:5001/image/two.jpg"
                  - "http://localhost:5001/image/three.jpg"
                  - "http://localhost:5001/image/four.jpg"
                location:
                  latitude: 123
                  longitude: 456

    post:
      parameters:
        - $ref: "#/components/parameters/BearerAuth"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                gender:
                  type: string
                sexual_preference:
                  type: string
                biography:
                  type: string
                latitude:
                  type: number
                  format: float
                longitude:
                  type: number
                  format: float
                location_city:
                  type: string
            example:
              gender: "male"
              sexual_preference: "female"
              biography: "Hi, I am John"
              latitude: 1.3521
              longitude: 103.8198
              location_city: "Singapore"
      responses:
        "200":
          description: Profile updated
